### ISSUE TITLE
add setting to configure xml file location

### ISSUE THREAD

**Issue by TylerLeonhardt** [TylerLeonhardt/vscode-powershell-test-adapter#3]
We need a configuration to change where the XML file is.

Right now it's hard coded to `TestExplorerResults.xml` in the root of the workspace

**Comment by nohwnd** [comment]
I think you meant `TestExplorerResults.xml`.

https://github.com/TylerLeonhardt/vscode-powershell-test-adapter/blob/master/src/pesterTests.ts#L61

**Comment by TylerLeonhardt** [comment]
Added.
