### ISSUE TITLE
Support "autorun"

### ISSUE THREAD

**Issue by TylerLeonhardt** [TylerLeonhardt/vscode-powershell-test-adapter#7]
* [ ]  watch the configuration for any changes that may affect the results of running the tests and emit an autorun event if necessary
* [ ]  watch the workspace for any changes to the source files and emit an autorun event if necessary

We should be careful with this because the test run doesn't happen in another process...

**Comment by bergmeister** [comment]
In Visual Studio land, they call this kind of feature "Live Unit Testing". I'm not a fan of that term but for consistency purposes it would probably be good to re-use the same name.

**Comment by TylerLeonhardt** [comment]
"autorun" is what it's called in the Test Explorer ecosystem. I'm just reusing the term used there.
